zuul:
  routes:
    auth:
      path: /auth-service/**
      serviceId: auth-service
    file:
      path: /file-service/**
      serviceId: file-service
    system:
      path: /system-service/**
      serviceId: system-service
    log:
      path: /log-service/**
      serviceId: log-service
    user:
      path: /user-service/**
      serviceId: user-service
      sensitiveHeaders:
    template:
      path: /template-service/**
      serviceId: template-service
    business:
      path: /business-service/**
      serviceId: business-service
    data:
      path: /data-service/**
      serviceId: data-service
    equipment:
      path: /equipment-service/**
      serviceId: equipment-service
    knowledge:
      path: /knowledge-service/**
      serviceId: knowledge-service
    statistics:
      path: /statistics-service/**
      serviceId: statistics-service
  ignored-services: '*'


session:
  domain: zuul-server

feign:
  hystrix:
    enabled: true


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #instance-id: ${spring.cloud.client.ip-address}:${random.value}
    metadata-map:
      user.name: ${define.security.name}
      user.password: ${define.security.password}
      management.context-path: ${server.servlet.context-path}/actuator

    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

    ## 监控地址 拼接  context-path
    home-page-url-path: ${server.servlet.context-path}
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health



jwt:
  exclude:
    urlPatterns:
      - /user-service/sso/login/checkSession
      - /user-service/sso/login/login
      - /template-service/.*
      - /data-service/.*
      - /file-service/.*
      - .*api-docs.*
      - .*swagger.*